### ISSUE TITLE
Increased RAM usage with v8.5.0 when many BCs are present (from 8.3.0)

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1268]

**Comment by payetvin** [comment]
Need the study used to create this issue.

**Comment by Milos-RTEi** [comment]
The network where we realized this potential ram increase is a confidential network belonging to our client.
He strictly forbids us to share it with anyone. 
@hugo-antoine-rtei maybe we can share it with RTE?

**Comment by payetvin** [comment]
It's fine if it's confidential we can do without it.
Can you at least communicate the number of binding constraints files or the size of the input/bindingconstraints directory ?
My main issue is: how much is "increased RAM usage", how many in Mo and percents compared to the 8.3 ?

I compared in details the 8.3, 8.5 and current develop branch memory usage/profile on 2 different studies, with dozens of binding constraints files and I didn't notice a huge difference. I can send you those results if you're interested.

**Comment by Milos-RTEi** [comment]
The number of constraints is 608. 
The size of the input/bindingconstraints directory is 1.5MB.
while running the study the RAM increase is:
8.5v  -> 18.8 GB
8.4.1v -> 19 GB
8.3.2v - > 19.1 GB
8.3.0v -> 18.7 GB
I have 32gB of RAM and if I have chrome with multiple tabs and other stuff running it breaks my simulation.
But the issue is I cannot reproduce low RAM consumption. 
I will investigate further to see if I can find out when (version) it happened. Each simulation is taking very long so it takes time.

**Comment by payetvin** [comment]
Only the loading part matters for the RAM consumption, you can stop when the solver starts to run as it's stable until the end of the execution.

**Comment by payetvin** [comment]
Not reproduced yet and not a priority.
We will keep studying RAM consumption on Antares to have a better understanding on it.

**Comment by payetvin** [comment]
Not reproduced yet and not a priority.
We will keep studying RAM consumption on Antares to have a better understanding on it.
