### ISSUE TITLE
Time-series produced by generators cannot be stored  with Antares v9.0.0

### ISSUE THREAD

**Issue by NeutrinoZeng** [AntaresSimulatorTeam/Antares_Simulator#2102]
**Description**
Time-series generator cannot store data in input with Antares v9.0.0

**How to Reproduce**
My Antares Simultor has been upgraded form v8.6.5 to v9.0.0.
In v8.6.5, the time-series generator works well. All the generated time-series of renewables or themal plants will be collected in input. Therefore, we could apply MC Scenario Builder to create N sets of deterministic scenario, for comparison between different schemes.
In v9.0.0, although the "Store in input" option keeps "Yes", all the generated time-series will not be stored in input anymore. It is worth mentioning that new time-series could be well stored in output and the simulation results are correct.

**Expected behavior**
In Antares v9.1.0 rc3, this problem still exists.
I recommmed developers pay attention to this problem, as the version of my study has been upgrage to v9.0.0 as well and cannot back to v8.6.5 (If somebody could tell me how to do it, I wll appreciate LOL ...)

**Screenshots and additional files**
If applicable, add screenshots to help explain your problem. You may also include a .zip file containing your study.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 9.0.0

**Additional context**

**Comment by flomnes** [comment]
Hi @NeutrinoZeng thanks for submitting this ticket. Unfortunately there is no way to downgrade a study, which is why we recommend users make a copy first.

In the logs you may have noticed a warning notice. Indeed, for generated TS to be stored in the input directory, it is necessary for the study version and the software version to match. For example 9.0 study with Antares 9.0.0 (or 9.0.x for any x) will work, while study 8.8 with Antares 9.0 won't.

The warning message is the following

> Stochastic TS stored in input parametrized. Disabling Store in input because study is not at latest version. Prevents writing data in unsupported format at the study version.

**Comment by flomnes** [comment]
We seem to have found a fix, see #2180
