### ISSUE TITLE
Enabling the specification of several rule curves for hydro reservoirs

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#215]
Today, in Antares, for a given area, only one set of time-series can be specified for the hydro reservoir of this area (this set consists in three daily time-series, corresponding to the minimum, average and maximum reservoir levels). This set of time-series is called "rule curves" and is then used for all the simulated Monte-Carlo years. 
![image](https://user-images.githubusercontent.com/53614116/113150980-f0276380-9234-11eb-9bcd-de59011c4f36.png)

The requested enhancement is to allow to specify several sets of rule curves for a given reservoir of a given zone. To build a given Monte-Carlo year, Antares would then select one of these sets of three time-series (either randomly or via a proper setting of the scenario builder).

This enhancement also requires GUI evolutions to provide the user with a table in which he can fill in several sets of rule curves. It also requires an evolution in the scenario builder to enable the user to specify which set is to be considered for a given MC year.

**Comment by sgatto** [comment]
### Question
Q1: the 3 colums are linked in the TS? It seems it should be the case, otherwise incoherences can arise i.e. lev.low > lev.high

Q2: what is the inteaction of the initial reservoir levels?

Q3; how should the TS be presented? three separate tables min, avg, max? A table of three columns?

Q4: at present the user cannot initialise min>max. What should be done if the TS are incoherent on this regard?

Q5: how should we treat the retrocompatibility? This point can be very costly depending on how we deal with it.

### Changes
three separate screen for each value in the Time-Series tab?

new entry in the scenario Builder

### Estimation
**6-8 man weeks**

**Comment by PPlessiez** [comment]
Thanks for the estimate!

Q1: Indeed, the three columns should be considered together, which explains why I would propose to group them as "sets"

Q2: Today, if not specified in the scenario builder, the initial reservoir level is drawn randomly around the average reservoir level on the first day of the initialization month, staying between the min and the max level.

Q3: I think we should consider the simplest approach from a GUI prospective, which seems to be the solution implying three separate tables. When a MC year is built, the same column number in each of these three tables should be selected. To be discussed.

Q4: An error should be issued (blocking problem for solving).

Q5: To be discussed. The cleanest way would be to ensure retrocompatibility by reading hydro levels from previous versions and feeding them in as columns in the new tables, but this depends on cost.
@sgatto Can you elaborate on this point?

**Comment by payetvin** [comment]
RTE-I does the job
