### ISSUE TITLE
Remove save functions (only GUI uses them)

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#2162]
- Study components (areas, links, binding constraints, etc.)
- Scenario builder
- Area sets
- Metadata : user's note, comments, antares.study, etc.

**Comment by JasonMarechal25** [comment]
I'm on the fence for this one.
On one hand if it is not used anymore it's just dead code that could be difficult to maintain
On the other hand we may need them later down the line

However since I don't foresee any usage soon, I'm ok to delete it. We can always recover the implementation from git later on

**Comment by pet-mit** [comment]
ANT-2115
