### ISSUE TITLE
Give the possibility to extract hydro pre-allocation results in debug mode

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#253]
**Need**
Today, the results of the pre-allocation hydro heuristics are not displayed to the used. However, they are already calculated during Antares solving and they could be easily displayed in additional results files (the generation of these files has already been developed in Antares for past debug purposes). It would be useful for result analysis to allow the Antares R&D team to activate the generation of these files if needed.

**Proposed enhancement**
Add a new "hydro-debug" boolean parameter in the "generaldata.ini" file in order to activate or deactivate the generation of these hydro pre-allocation result files when running an Antares simulation.

**Comment by flomnes** [comment]
This is minor, but I recommend this instead
```ini
[debug]
hydro = true
```

So that if more debug info is required, it can be placed under this new section.

**Comment by JMJ-rte** [comment]
As discussed this morning 3 phases are required to deal with this feature: 
- phase 1 : add the new parameter [debug] hydro in order to have access to these data with the same exe file. (already done by Florian) ;
- phase 2 : document the different data that are delivered depending on hydro configuration ;
- phase 3 (to be completed in the feature) : to modify if necessary the list of the data delivered
