### ISSUE TITLE
Inactive MC builder rulesets throw warnings

### ISSUE THREAD

**Issue by jorritvm** [AntaresSimulatorTeam/Antares_Simulator#4]
If the TS draw for a disabled thermal unit is predefined in a ruleset this will throw a warning upon executing the simulation. However, it seems this warning is generated for every MC ruleset, and not just for the active one.

![issue](https://user-images.githubusercontent.com/44178217/65146882-31726c80-da1d-11e9-80f1-3174db186806.png)

More generally, I've just built a model with 2000 thermal units, a lot of which are disabled, and predetermined the draw for each of the 1320MC years. This results in hundreds of thousands of warnings generated, slowing down antares quite a lot. Maybe this warning / check can just be cancelled?

**Comment by guilpier-code** [comment]
Hello jorritvm,
Thanks again for pointing this issue.
As in the previous one, a fix for this will be available in version 8.0 coming very soon.
What is done in v8.0 regarding this issue :
- For a disabled thermal cluster, a warning is triggered only if this cluster is given a time series number in a scenario in the active rule.
- Further more, the warnings are less numerous : instead of triggering a warning for each year a disabled cluster is given a TS number (in the active rule), we send only one warning that lists the 10 first years (at most) the clusters is needed.
