### ISSUE TITLE
[Antares V8.3.2] Default filtering values for binding constraints reset at each save

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/Antares_Simulator#915]
**Description**
When a user sets the filtering parameters for the binding constraints output (in bindingconstraints.ini), these parameters are reset when the study is saved via the GUI, and the default parameters (create the output files for each granularity, for mc-ind and mc-all) are reset.

**How to Reproduce**
In a study with binding constraints, set the filtering of BC outputs to a value different from the default value. Then change the study via the GUI (e.g. change the location of an area in the map) and save the study. The output parameters for BC will then be reset to their default value.

**Expected behavior**
The output parameters set by the user for the BC output should be kept even when the study is saved via the GUI.

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.3.2

**Comment by flomnes** [comment]
I think I know what your problem is. Please correct me if I'm wrong.

1. You load the study in the GUI.
2. You edit **bindingconstraints.ini** with a text editor
3. You save the study in the GUI
4. Your changes from step 2. are erased after step 3.

The only way to avoid this is to reload the study after step 2. Otherwise, the old values are saved at step 3.

**Comment by PPlessiez** [comment]
After retest, the behavior you describe is correct, and reloading the study after step 2 allows to avoid the reset.
The corresponding issue can be closed.
